apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carta-mongodb-data
  namespace: carta
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carta-user-data
  namespace: carta
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carta-test-files
  namespace: carta
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi 