apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carta-test-files
  namespace: carta
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath 